name: mlkit_esercizio_1
description: MLKit Esercizio 1

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # google_ml_kit: ^0.13.0 # (tutto incluso)
  google_mlkit_commons: ^0.2.0
  google_mlkit_barcode_scanning: ^0.5.0

  image_picker: ^0.8.6
  path: ^1.8.2
  path_provider: ^2.0.11
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true